name: amritha_ayurveda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5

  # Networking
  dio: ^5.7.0
  retrofit: 4.1.0

  # Routing
  go_router: ^14.6.0

  # Local Storage
  shared_preferences: ^2.5.4

  # Utilities
  intl: ^0.19.0
  google_fonts: ^6.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  json_annotation: 4.9.0
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: 2.4.0
  json_serializable: 6.8.0
  retrofit_generator: 8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
